// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nkolosov/whip-round/internal/hash (interfaces: HashManager)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHashManager is a mock of HashManager interface.
type MockHashManager struct {
	ctrl     *gomock.Controller
	recorder *MockHashManagerMockRecorder
}

// MockHashManagerMockRecorder is the mock recorder for MockHashManager.
type MockHashManagerMockRecorder struct {
	mock *MockHashManager
}

// NewMockHashManager creates a new mock instance.
func NewMockHashManager(ctrl *gomock.Controller) *MockHashManager {
	mock := &MockHashManager{ctrl: ctrl}
	mock.recorder = &MockHashManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashManager) EXPECT() *MockHashManagerMockRecorder {
	return m.recorder
}

// CheckPasswordHash mocks base method.
func (m *MockHashManager) CheckPasswordHash(arg0, arg1 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPasswordHash", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckPasswordHash indicates an expected call of CheckPasswordHash.
func (mr *MockHashManagerMockRecorder) CheckPasswordHash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPasswordHash", reflect.TypeOf((*MockHashManager)(nil).CheckPasswordHash), arg0, arg1)
}

// HashPassword mocks base method.
func (m *MockHashManager) HashPassword(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockHashManagerMockRecorder) HashPassword(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockHashManager)(nil).HashPassword), arg0)
}
